# Generated by Django 5.2 on 2025-05-28 21:27

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('max_floor', models.IntegerField(default=1)),
                ('floor', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=20)),
                ('atk', models.IntegerField(default=main.models.default_atk)),
                ('skill1', models.JSONField(default=main.models.default_skill1)),
                ('skill2', models.JSONField(default=main.models.default_skill2)),
                ('skill3', models.JSONField(default=dict)),
                ('skill4', models.JSONField(default=dict)),
                ('inventory', models.JSONField(default=dict)),
                ('achievements', models.JSONField(default=dict)),
                ('monster', models.JSONField(default=dict)),
                ('defe', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=1)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
