# Generated by Django 5.2 on 2025-04-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='atk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='defe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
