# Generated by Django 5.2.1 on 2025-05-31 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_player_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='teste',
        ),
    ]
