# Generated by Django 5.2 on 2025-04-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_player_atk_player_defe_player_exp_player_hp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
