# Generated by Django 5.2 on 2025-04-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='kill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.JSONField(default=dict),
        ),
    ]
