# Generated by Django 5.2.1 on 2025-05-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_player_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='max_exp',
            field=models.IntegerField(default=60),
        ),
    ]
