# Generated by Django 5.2.1 on 2025-05-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_player_kill_player_score_player_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='inventory',
            field=models.JSONField(default=dict),
        ),
    ]
