# Generated by Django 5.2.1 on 2025-05-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_player_max_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='max_exp',
            field=models.IntegerField(default=100),
        ),
    ]
