# Generated by Django 5.2.1 on 2025-06-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_player_max_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='levelup',
            field=models.BooleanField(default=True),
        ),
    ]
