# Generated by Django 5.2.1 on 2025-06-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_player_levelup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hp',
            field=models.IntegerField(default=50),
        ),
    ]
