# Generated by Django 5.2.1 on 2025-05-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_player_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='achievements',
            field=models.JSONField(default=dict),
        ),
    ]
