# Generated by Django 5.2.1 on 2025-06-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_player_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='max_exp',
            field=models.IntegerField(default=60),
        ),
    ]
