# Generated by Django 5.2 on 2025-05-24 21:31

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_player_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='andar',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='monster',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='player',
            name='atk',
            field=models.IntegerField(default=main.models.default_atk),
        ),
        migrations.AlterField(
            model_name='player',
            name='hp',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='skills',
            field=models.JSONField(default=main.models.default_skills),
        ),
        migrations.AlterField(
            model_name='player',
            name='speed',
            field=models.IntegerField(default=1),
        ),
    ]
