# Generated by Django 5.2 on 2025-05-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_player_andar_player_monster_alter_player_atk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='andar',
            new_name='floor',
        ),
        migrations.AddField(
            model_name='player',
            name='max_floor',
            field=models.IntegerField(default=1),
        ),
    ]
